server:
  port: 8090
spring:
  application:
    name: payment-service
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      password: 241119
      client-type: jedis
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.alibaba.nacos: WARN
